// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDRvYcSFDT8-2QYYOIMtbHJ5ja1xOuYys',
    appId: '1:792723252094:web:f44a545bfe8a83b77e892f',
    messagingSenderId: '792723252094',
    projectId: 'skincare-69935',
    authDomain: 'skincare-69935.firebaseapp.com',
    storageBucket: 'skincare-69935.firebasestorage.app',
    measurementId: 'G-DXVK14R6V9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd30EdHxtBnp_a5YqO1s0aCRLxoQP9Kbc',
    appId: '1:792723252094:android:c1973ff18bfb979b7e892f',
    messagingSenderId: '792723252094',
    projectId: 'skincare-69935',
    storageBucket: 'skincare-69935.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAmqCZUWMg91ge58KXfbiIJ1S_u3CuC8E',
    appId: '1:792723252094:ios:74593ae8478aef237e892f',
    messagingSenderId: '792723252094',
    projectId: 'skincare-69935',
    storageBucket: 'skincare-69935.firebasestorage.app',
    iosBundleId: 'com.example.glowvana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAmqCZUWMg91ge58KXfbiIJ1S_u3CuC8E',
    appId: '1:792723252094:ios:74593ae8478aef237e892f',
    messagingSenderId: '792723252094',
    projectId: 'skincare-69935',
    storageBucket: 'skincare-69935.firebasestorage.app',
    iosBundleId: 'com.example.glowvana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDRvYcSFDT8-2QYYOIMtbHJ5ja1xOuYys',
    appId: '1:792723252094:web:e257a179dfb806107e892f',
    messagingSenderId: '792723252094',
    projectId: 'skincare-69935',
    authDomain: 'skincare-69935.firebaseapp.com',
    storageBucket: 'skincare-69935.firebasestorage.app',
    measurementId: 'G-2TJDB8QHS8',
  );
}
